### ISSUE TITLE
聊天软件的文件传输实验总是失败

### ISSUE THREAD

**Issue by EveChang** [4u1kto/QTExample#1]
如何在自己电脑上实现文件传输实验呢？
我在自己的电脑上进行传输时，总是跳出多个界面，而且不能成功
![default](https://user-images.githubusercontent.com/26034310/40963456-2c0bd614-68db-11e8-8a77-29d84a76971e.JPG)

**Comment by 4u1kto** [comment]
弹出多个界面可能是因为connect多次造成的，
文件传输失败的原因不好定位，不知道你走的什么协议，FTP?HTTP?TCP?

**Comment by EveChang** [comment]
我用的TCP协议

**Comment by EveChang** [comment]
我用的TCP协议

**Comment by 4u1kto** [comment]
方便的话把代码push上来

**Comment by EveChang** [comment]
我就是用的QTExample里CH18 MyselfQQ的代码 只有文件传输实验有问题的

**Comment by 4u1kto** [comment]
这个需要启动两个程序才能看的出来效果，知道原理就行了。
我也是拷贝的书里的代码，没实际运行过。
